# Generated by Django 4.2.5 on 2023-09-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('et_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='created_at',
            new_name='date_time',
        ),
    ]
